import = [
  #"~/.config/alacritty/themes/ubuntu.toml"
  #"~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[window]

option_as_alt = "Both"

opacity = 0.85

padding.x = 1
padding.y = 0

decorations = "None"
decorations_theme_variant = "Dark"

[font]

normal.family = "MesloLGS NF"
italic.family = "MesloLGS NF"
bold.family = "MesloLGS NF"
bold_italic.family = "MesloLGS NF"
normal.style = "Regular"

size = 15.0

[shell]
program = "/bin/zsh"

#program = "/opt/homebrew/bin/tmux"
#args = ["new-session", "-A", "-s", "main"]

[keyboard]

bindings = [
  { key = "T", mods = "Command", action = "ReceiveChar" },
  { key = "K", mods = "Command", action = "ClearHistory" }
]

[scrolling]
history = 50000

[env]
term = "xterm-256color"
